version: '3.8'
services: 
  nginx:
    image: 528490145188.dkr.ecr.us-east-2.amazonaws.com/nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks: 
      - pebi
  app:
    build:
      args:
         user: pebi
         uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: 528490145188.dkr.ecr.us-east-2.amazonaws.com/app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php:/usr/local/etc/php
    networks:
      - pebi
  mysql:
    image: 528490145188.dkr.ecr.us-east-2.amazonaws.com/mysql:5.7
    restart: unless-stopped
    environment: 
      MYSQL_DATABASE: pebi
      MYSQL_USER: pebi
      MYSQL_PASSWORD: secret 
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - pebi
networks:
    pebi: